trigger:
- main

resources:
  repositories:
    - repository: self

stages:
- stage: Build
  jobs:
    - template: matrix-template.yml
      parameters:
        matrix: ${{ fromYaml(file('matrices/demo-matrix.yml')).matrix }}
